services:
  miniature-muster:
    build: .
    restart: always
    container_name: miniature-muster_nodejs
    pull_policy: build
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST_URI=http://localhost:3000
      - DB_TYPE=json
    ports:
      - 3000:3000
